### ISSUE TITLE
Improve Git workflow

### ISSUE THREAD

**Issue by nnarain** [nnarain/gameboycore-python#18]
Git workflow needs improvement.

Builds fail when pushing to `master` because commits on the master branch trigger CI pushes to PyPi which fail because the setup.py version isn't bumped.

* Repos default branch should be `devel`. 
* `master` is used for tagged commits only

**Comment by max-vogler** [comment]
Hey @nnarain!

You probably already evaluated this option, but just in case you haven't: Instead of having two branches, [Travis can also push to PyPI only on tagged commits](https://docs.travis-ci.com/user/deployment/releases/). You can achieve this by adding the following to your build stage in .travis-ci.yml:

```yaml
  on:
    tags: true
```

Doing this you wouldn't need to add another branch.

**Comment by nnarain** [comment]
I've been thinking about different git workflows and that option totally slipped my mind. I use in `gameboycore`. 

Thanks!
